spring.application.name=linkedin
spring.database.url=jdbc:mysql://localhost:3306/linkedin?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.database.password=root
spring.jpa.hibernate.ddl-auto=create