package com.linkedin.linkedin.service;

import com.linkedin.linkedin.dto.AuthenticationResponseBody;
import com.linkedin.linkedin.dto.RegisterRequest;
import com.linkedin.linkedin.exception.EmailAlreadyExistsException;
import com.linkedin.linkedin.model.AuthenticateUser;
import com.linkedin.linkedin.repository.AuthenticationUserRepository;
import com.linkedin.linkedin.utils.Encoder;
import org.springframework.stereotype.Service;

import java.util.Optional;
import java.util.UUID;

@Service
public class AuthenticationService {

    private final AuthenticationUserRepository repo;
    private final Encoder encoder;

    public AuthenticationService(AuthenticationUserRepository repo, Encoder encoder) {
        this.repo = repo;
        this.encoder = encoder;
    }

    public Optional<AuthenticateUser> getUser(String email) throws IllegalArgumentException
    {
        return AuthenticationUserRepository.findByEmail(email);
    }
    
    public AuthenticationResponseBody register(RegisterRequest registerRequestBody) {
        // Check if user already exists
        Optional<AuthenticateUser> existingUser = AuthenticationUserRepository.findByEmail(registerRequestBody.getEmail());
        if (existingUser!=null && existingUser.isPresent()) {
            throw new EmailAlreadyExistsException("User with this email already exists");
        }
        
        // Encode the password
        String encodedPassword = encoder.encode(registerRequestBody.getPassword());
        
        // Create and save the new user
        AuthenticateUser newUser = new AuthenticateUser(
            encodedPassword,
            registerRequestBody.getEmail(),
            null // ID will be generated by the database
        );
        
        AuthenticateUser savedUser = repo.save(newUser);
        
        // Generate a simple token (in a real app, you'd use JWT or similar)
        String token = UUID.randomUUID().toString();
        
        // Return the response with user details and token
        return new AuthenticationResponseBody(
            token,
            "User registered successfully"
        );
    }
}
